### ISSUE TITLE
User Story: Access Star Wars Music for Meditation Events

### ISSUE THREAD

**Issue by AmandaCIdev** [violaberg/star-wars-hackathon-2024#23]
As a ***user*** I can ***access Star Wars music tailored for different meditation events*** so that I can ***enhance my meditation experience with thematic music.***

### Acceptance criteria:

1. Event-Specific Playlists: Users can access curated playlists of Star Wars music that are tailored for different types of meditation events, such as relaxation, focus, or sleep.

2. Streaming and Downloading: Users can stream music directly from the website or download it for offline use during meditation sessions. (Won't have?)

3. Schedule Integration: Users can view and join scheduled meditation events that feature specific Star Wars music playlists, with calendar integration and reminders.

4. Search and Filter by Theme: Users can search for and filter meditation music by themes such as "Jedi Training", "Sith Meditation", or "Galactic Relaxation" to find the perfect music for their session.

**Comment by AmandaCIdev** [comment]
Sound file links:

1. Jedi theta binaural beats | https://iamares.bandcamp.com/track/10-min-jedi-meditation-binaural-beats-ambient-music (bandcamp)
2. Obi-Wan in the Jedi temple| https://star-wars.ambient-mixer.com/jedi-temple-meditation-with-ob (ambient mixer)
Meditate in the Jedi Temple | https://star-wars.ambient-mixer.com/jedi-temple (ambient mixer)
3. Sound Bath | https://archive.org/details/sw-library-5-2-22/SW-Library-5-2-22.mp3 (Internet Archive HTML5 Uploader 1.6.4)
4. Star Wars Sounds | https://www.soundboard.com/sb/starwars (soundboard nothing but sound)
5. Star Wars The Imperial March ( Darth Vader's Theme) | https://archive.org/details/StarWarsTheImperialMarchDarthVadersTheme (Internet Archive HTML5 Uploader 1.6.4)
6. Star Wars - Theme Song | https://archive.org/details/tvtunes_4617 (Internet Archive HTML5 Uploader 1.6.4)
7. Jar Jar Binks Soundboard | https://www.voicy.network/official-soundboards/movies/jar-jar-binks (voicy)

**Comment by craigallendev** [comment]
Across the stars love theme from star wars attack of the clones https://open.spotify.com/track/3rUMH7i22tlkymhDPOmXUv?si=e7945cc121f14fe7

**Comment by craigallendev** [comment]
Anakins Theme 
https://open.spotify.com/track/61ny12xki8cVUKP46nXp6Z?si=6b284725dd39461c

**Comment by craigallendev** [comment]
yoda and the younglings https://open.spotify.com/track/5OyhsSqaRE8w7c1hq17DfN?si=fdb138bb0da646de

**Comment by craigallendev** [comment]
Ahsoka Lives https://open.spotify.com/track/7Gq4mTdhrYlY5dHy2UooRH?si=27e6538ce25d4f29
