### ISSUE TITLE
Project Wireframes

### ISSUE THREAD

**Issue by MBilalQureshi** [violaberg/star-wars-hackathon-2024#3]
As a ***user*** I can ***create project wireframes*** so that I can ***visually see the design of the website, and have a reference of what I am going to build***.

### Acceptance criteria:
1. Design wireframes as blueprints that capture the project's primary goal keeping better user experience and responsiveness in mind.

**Comment by craigallendev** [comment]
https://www.figma.com/design/yeOJrmAh354JEa1FVCS9ON/Star-Wars-Hackathon?node-id=0%3A1&t=mkvUodHSysUiMx0r-1 heres what i have started let me know what you guys think?
