### ISSUE TITLE
Project Favicon

### ISSUE THREAD

**Issue by MBilalQureshi** [violaberg/star-wars-hackathon-2024#5]
As a ***user*** I like ***my site to have a favicon*** so that ***It can be distinguished clearly when multiple tabs are open***.

### Acceptance criteria:
1. Favicon should be available on all the pages.
2. The created favicon should be Star Wars themed.

**Comment by AmandaCIdev** [comment]
I have some favicon images I created that I want you guys to check out...see if you think any would work.
![IMG_0535](https://github.com/violaberg/star-wars-hackathon-2024/assets/154023617/463688a9-ecae-43b5-82aa-320e731decc0)
![IMG_0537](https://github.com/violaberg/star-wars-hackathon-2024/assets/154023617/de802ca0-1c77-4603-a76e-0623fdfbee3d)
![IMG_0538](https://github.com/violaberg/star-wars-hackathon-2024/assets/154023617/535eb7f1-4345-4bd4-8df5-36d1f7c37b41)
![IMG_0539](https://github.com/violaberg/star-wars-hackathon-2024/assets/154023617/456f21ef-aebe-4fe8-9d66-1cb0f33e6c4e)
![IMG_0540](https://github.com/violaberg/star-wars-hackathon-2024/assets/154023617/53a36eaa-b0ef-4af0-876c-bd30fa897c20)
![IMG_0541](https://github.com/violaberg/star-wars-hackathon-2024/assets/154023617/1e9a75a0-3670-458c-b7df-9b2a516aa859)
![IMG_0542](https://github.com/violaberg/star-wars-hackathon-2024/assets/154023617/2b3e6c24-a932-446f-b516-79ed7af77d9b)
![IMG_0543](https://github.com/violaberg/star-wars-hackathon-2024/assets/154023617/a9f060e6-fa21-429d-bcbc-009b1c9df078)
![IMG_0544](https://github.com/violaberg/star-wars-hackathon-2024/assets/154023617/7670430e-4498-4ba4-af14-29f52d8613eb)
![IMG_0545](https://github.com/violaberg/star-wars-hackathon-2024/assets/154023617/f1e117d7-29f2-49d4-a046-8161af1cdf25)
![IMG_0546](https://github.com/violaberg/star-wars-hackathon-2024/assets/154023617/7d35e2bb-5940-4ac9-8563-cbd64d670efc)

**Comment by AmandaCIdev** [comment]
a few more
![IMG_0548](https://github.com/violaberg/star-wars-hackathon-2024/assets/154023617/a964f98d-b04e-4d63-b168-c94f2912745c)

![IMG_0550](https://github.com/violaberg/star-wars-hackathon-2024/assets/154023617/d7642f11-834b-45d9-9c43-a5f054ed813b)
![IMG_0551](https://github.com/violaberg/star-wars-hackathon-2024/assets/154023617/8a77b739-7591-4873-be74-a51ed31e7ad8)
![IMG_0552](https://github.com/violaberg/star-wars-hackathon-2024/assets/154023617/0522d249-d5e3-489e-937d-47a8b3134d85)
![IMG_0553](https://github.com/violaberg/star-wars-hackathon-2024/assets/154023617/c0a0670a-33b9-435e-8259-ddb0d8a8b196)
![IMG_0554](https://github.com/violaberg/star-wars-hackathon-2024/assets/154023617/c08a97a6-ecd3-4122-b38b-421c666042e5)

**Comment by AmandaCIdev** [comment]
<img width="1114" alt="Screenshot 2024-05-23 at 00 41 36" src="https://github.com/violaberg/star-wars-hackathon-2024/assets/154023617/91268dae-8454-458a-9c34-a22e5a4b6d5d">

**Comment by AmandaCIdev** [comment]
![IMG_0559](https://github.com/violaberg/star-wars-hackathon-2024/assets/154023617/f8082c55-dd89-4981-8722-c82a3cf08732)

**Comment by violaberg** [comment]
Favicon/ logo decided
